site_name: OhMyGrid
site_url: 'https://ohmygrid.org/'
site_description: A global community of citizen contributors creates and maintains data on the core infrastructures of our modern society. Let's empower them! 
repo_name: 'OhMyGrid'
repo_url: 'https://github.com/open-energy-transition/Oh-my-Grid'

nav:
  - The Initiative : index.md
  - Impact: impact.md
  - Starter-Kit Tutorial: starter-kit.md
  - Map It📍: map-it.md
  - Tools and Strategies: tools.md
  #- Guidelines : guidelines.md
  - Curated Grid Maps: awesome.md
  - Our Progress : progress.md
  - Blog:
      2025:
        - "Liberate the Grid": blog/firstrename.md

copyright:    <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">
      Creative Commons Attribution 4.0 International License   </a> -  <a href="https://ohmygrid.org/privacy-policy/"> Read our Privacy Policy</a> 

theme:
  name: material
  custom_dir: docs/overrides
  favicon: images/logo.png
  logo: images/logo.png
  palette:
    # Light Mode
    - scheme: default
      primary: custom
      accent: indigo
      toggle: false 
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - search.highlight
    - search.suggest
    - navigation.top
    - content.image.zoom

extra_css:
    - stylesheets/extra.css
    - stylesheets/landing.css
    - stylesheets/blog.css
    - https://cdn.jsdelivr.net/npm/featherlight@1.7.14/release/featherlight.min.css

extra:
  generator: false

extra_javascript:
  - js/umami.js


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - markdown.extensions.md_in_html
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true


