name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache 
          restore-keys: |
            mkdocs-material-
      - run: |
          wget https://raw.githubusercontent.com/open-energy-transition/Awesome-Electric-Grid-Mapping/main/README.md -O- | \
          sed '1s/^#.*/<div class="page-headers">\n 🗺️ Curated Grid Maps\n\n<a href="https:\/\/github.com\/open-energy-transition\/Awesome-Electric-Grid-Mapping" class="github-link">🔗 View on GitHub<\/a>\n<\/div>\n/' > ./docs/awesome.md
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force
      
