name: Update line length
on:
  workflow_dispatch: {} # enables manual trigger
  schedule:
    - cron: '0 3 * * 0' # runs every Sunday at 3 UTC (1 hour after tower count)
permissions:
  contents: write
jobs:
  fetch-line-length:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq bc
      - id: run-query
        name: Run Overpass line length query
        run: |
          cat << 'EOF' > query.overpassql
          [out:json][timeout:900];
          
          node["power"="tower"](user_touched:"Andreas Hernandez","Tobias Augspurger","davidtt92","Mwiche","relaxxe") -> .towers;
          node["power"="pole"](user_touched:"Andreas Hernandez","Tobias Augspurger","davidtt92","Mwiche","relaxxe") -> .poles;
          
          node["power"="tower"](user: "Russ","map-dynartio","overflorian","nlehuby","ben10dynartio","InfosReseaux")(newer:"2025-03-01T00:00:00Z")->.their_towers;
          
          (
            node.towers;
            node.poles;
          ) -> .my_nodes;
          
          way["power"="line"](bn.my_nodes)-> .connected_ways;
          way["power"="line"](bn.their_towers)-> .theirconnected_ways;
          
          (
            .my_nodes;
            .connected_ways;
            .theirconnected_ways;
            .their_towers;
          );
          
          out body;
          >;
          out skel qt;
          EOF
          
          # Fetch data from Overpass API
          echo "Fetching data from Overpass API..."
          curl -s --data-urlencode "data@query.overpassql" \
            https://overpass-api.de/api/interpreter > overpass_data.json
          
          # Check if we got valid JSON
          if ! jq empty overpass_data.json 2>/dev/null; then
            echo "Error: Invalid JSON response from Overpass API"
            cat overpass_data.json
            exit 1
          fi
          
          # Create Node.js script to calculate line length
          cat << 'NODEJS' > calculate_length.js
          const fs = require('fs');
          
          // Haversine distance calculation function
          function haversineDistance(coord1, coord2) {
            const [lat1, lon1] = coord1;
            const [lat2, lon2] = coord2;
            const R = 6371; // Earth radius in km
            const dLat = (lat2 - lat1) * Math.PI / 180;
            const dLon = (lon2 - lon1) * Math.PI / 180;
            const a =
              Math.sin(dLat/2) * Math.sin(dLat/2) +
              Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) *
              Math.sin(dLon/2) * Math.sin(dLon/2);
            const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
            return R * c;
          }
          
          // Read the Overpass API response
          const data = JSON.parse(fs.readFileSync('overpass_data.json', 'utf8'));
          
          // Build node map & prepare way list
          const nodes = {};
          const ways = [];
          
          data.elements.forEach(el => {
            if (el.type === 'node' && el.tags && (el.tags.power === 'tower' || el.tags.power === 'pole')) {
              nodes[el.id] = [el.lat, el.lon];
            } else if (el.type === 'way' && el.tags && el.tags.power === 'line') {
              ways.push(el);
            }
          });
          
          let totalLength = 0;
          let wayCount = 0;
          
          ways.forEach(way => {
            // collect only user nodes in sequence that exist in the returned nodes
            const towerCoords = way.nodes
              .filter(id => nodes[id]) // Only consider node IDs that were in the .my_nodes set
              .map(id => nodes[id]);
          
            if (towerCoords.length >= 2) {
              wayCount++;
              let segLength = 0;
              for (let i = 0; i < towerCoords.length - 1; i++) {
                segLength += haversineDistance(towerCoords[i], towerCoords[i+1]);
              }
              totalLength += segLength;
            }
          });
          
          console.log(JSON.stringify({
            totalLength: Math.round(totalLength),
            wayCount: wayCount,
            nodeCount: Object.keys(nodes).length
          }));
          NODEJS
          
          # Run the calculation
          echo "Calculating line length..."
          RESULT=$(node calculate_length.js)
          LENGTH=$(echo $RESULT | jq -r '.totalLength')
          WAY_COUNT=$(echo $RESULT | jq -r '.wayCount')
          NODE_COUNT=$(echo $RESULT | jq -r '.nodeCount')
          
          echo "Total length: ${LENGTH} km"
          echo "Ways processed: ${WAY_COUNT}"
          echo "Nodes found: ${NODE_COUNT}"
          
          echo "length=$LENGTH" >> $GITHUB_OUTPUT
          
          # Initialize variables with fallback values
          TOTAL_GLOBAL=0
          EXCLUDED_LOW=0
          MEDIUM_HIGH_TOTAL=0
          PERCENTAGE="0.00"
          
          # Fetch OpenInfraMap stats for percentage calculation
          echo "Fetching OpenInfraMap global stats..."
          if curl -s https://openinframap.org/stats > openinframap_stats.html; then
            # Extract voltage data and calculate medium-high voltage total
            cat << 'NODEJS2' > calculate_percentage.js
            const fs = require('fs');
            
            // Function to decode HTML entities
            function decodeHtmlEntities(text) {
              const entities = {
                '&nbsp;': ' ',
                '&ndash;': '-',
                '&mdash;': '-',
                '&amp;': '&',
                '&lt;': '<',
                '&gt;': '>',
                '&quot;': '"',
                '&#39;': "'",
                '&hellip;': '...'
              };
              return text.replace(/&[a-zA-Z0-9#]+;/g, match => entities[match] || match);
            }
            
            try {
              const html = fs.readFileSync('openinframap_stats.html', 'utf8');
              console.error('HTML content length:', html.length);
              
              // Extract table rows - look for pattern: voltage | length | percentage
              const tableRowRegex = /<tr[^>]*>[\s\S]*?<td[^>]*>([^<]+)<\/td>[\s\S]*?<td[^>]*>([^<]+)<\/td>[\s\S]*?<td[^>]*>([^<]+)<\/td>[\s\S]*?<\/tr>/gi;
              
              let totalGlobalKm = 0;
              let excludedLowVoltageKm = 0;
              let match;
              
              console.error('Starting to parse table rows...');
              
              while ((match = tableRowRegex.exec(html)) !== null) {
                // Decode HTML entities in all captured groups
                const voltage = decodeHtmlEntities(match[1].trim());
                const lengthStr = decodeHtmlEntities(match[2].trim());
                const percentage = decodeHtmlEntities(match[3].trim());
                
                console.error(`Found row: ${voltage} | ${lengthStr} | ${percentage}`);
                console.error(`Decoded row: ${voltage} | ${lengthStr} | ${percentage}`);
                
                // Extract km value from length string - handle both regular spaces and non-breaking spaces
                const kmMatch = lengthStr.match(/([\d,\s]+)\s*km/i);
                if (kmMatch) {
                  // Remove all non-digit and non-comma characters, then parse
                  const cleanedNumber = kmMatch[1].replace(/[^\d,]/g, '');
                  const km = parseInt(cleanedNumber.replace(/,/g, ''));
                  console.error(`Parsed "${lengthStr}" -> cleaned "${cleanedNumber}" -> ${km} km`);
                  
                  // Check if this is the Total row
                  if (voltage.toLowerCase().includes('total')) {
                    totalGlobalKm = km;
                    console.error(`Found total: ${km} km`);
                  }
                  // Check if this is a low voltage category to exclude (first 3 rows)
                  else if (voltage.includes('0 V - 9 kV') || 
                           voltage.includes('10 kV - 24 kV') || 
                           voltage.includes('25 kV - 51 kV')) {
                    excludedLowVoltageKm += km;
                    console.error(`Excluding ${voltage}: ${km} km`);
                  }
                } else {
                  console.error(`Could not match km pattern in: "${lengthStr}"`);
                }
              }
              
              const mediumHighVoltageKm = totalGlobalKm - excludedLowVoltageKm;
              
              console.error(`Summary: Total=${totalGlobalKm}, Excluded=${excludedLowVoltageKm}, Medium-High=${mediumHighVoltageKm}`);
              
              // Only output result if we have valid data
              if (totalGlobalKm > 0 && mediumHighVoltageKm > 0) {
                console.log(JSON.stringify({
                  success: true,
                  totalGlobalKm: totalGlobalKm,
                  excludedLowVoltageKm: excludedLowVoltageKm,
                  mediumHighVoltageKm: mediumHighVoltageKm
                }));
              } else {
                console.log(JSON.stringify({
                  success: false,
                  error: `Could not parse valid data. Total: ${totalGlobalKm}, Excluded: ${excludedLowVoltageKm}`
                }));
              }
              
            } catch (error) {
              console.error('Error parsing OpenInfraMap stats:', error);
              console.log(JSON.stringify({
                success: false,
                error: error.message
              }));
            }
          NODEJS2
            
            STATS_RESULT=$(node calculate_percentage.js)
            SUCCESS=$(echo $STATS_RESULT | jq -r '.success // false')
            
            if [ "$SUCCESS" = "true" ]; then
              TOTAL_GLOBAL=$(echo $STATS_RESULT | jq -r '.totalGlobalKm')
              EXCLUDED_LOW=$(echo $STATS_RESULT | jq -r '.excludedLowVoltageKm')
              MEDIUM_HIGH_TOTAL=$(echo $STATS_RESULT | jq -r '.mediumHighVoltageKm')
              
              # Calculate percentage with better precision
              PERCENTAGE=$(echo "scale=3; $LENGTH * 100 / $MEDIUM_HIGH_TOTAL" | bc -l)
              # Round to 2 decimal places
              PERCENTAGE=$(printf "%.2f" $PERCENTAGE)
              
              echo "Global total: ${TOTAL_GLOBAL} km"
              echo "Excluded low voltage: ${EXCLUDED_LOW} km"
              echo "Medium-high voltage total: ${MEDIUM_HIGH_TOTAL} km"
              echo "Team contribution: ${LENGTH} km (${PERCENTAGE}%)"
            else
              echo "Warning: Could not fetch or parse OpenInfraMap stats. Using length data only."
              echo "Error: $(echo $STATS_RESULT | jq -r '.error // "Unknown error"')"
            fi
          else
            echo "Warning: Could not fetch OpenInfraMap stats. Using length data only."
          fi
          
          # Create the JSON file - always include length, add percentage data if available
          mkdir -p docs/data
          if [ "$MEDIUM_HIGH_TOTAL" -gt 0 ] 2>/dev/null; then
            cat << JSON > docs/data/line-length.json
          {
            "lengthKm": $LENGTH,
            "totalGlobalKm": $TOTAL_GLOBAL,
            "mediumHighVoltageKm": $MEDIUM_HIGH_TOTAL,
            "percentageOfMediumHigh": $PERCENTAGE,
            "updated": "$(date --utc +%Y-%m-%dT%H:%M:%SZ)"
          }
          JSON
          else
            cat << JSON > docs/data/line-length.json
          {
            "lengthKm": $LENGTH,
            "totalGlobalKm": null,
            "mediumHighVoltageKm": null,
            "percentageOfMediumHigh": null,
            "updated": "$(date --utc +%Y-%m-%dT%H:%M:%SZ)"
          }
          JSON
          fi
          
          # Clean up temporary files
          rm -f query.overpassql overpass_data.json calculate_length.js openinframap_stats.html calculate_percentage.js
          
      - name: Commit & push if changed
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: "chore: weekly line length update (${{ steps.run-query.outputs.length }} km)"
          add: docs/data/line-length.json